% -------------------------------------------------------------------
%  Generated by MATLAB on 18-Aug-2024 21:12:04
%  MATLAB version: 23.2.0.2668659 (R2023b) Update 9
% -------------------------------------------------------------------
saveVarsMat = load('AngleTable.mat');

C_LUT_AngleTable_sng_Null = saveVarsMat.C_LUT_AngleTable_sng_Null; % <1x1 Simulink.Parameter> C_LUT_AngleTable_sng_Null.Value 中的元素太多

C_LUT_SinTable_sng_Null = saveVarsMat.C_LUT_SinTable_sng_Null; % <1x1 Simulink.Parameter> C_LUT_SinTable_sng_Null.Value 中的元素太多

clear saveVarsMat;
