% -------------------------------------------------------------------
%  Generated by MATLAB on 11-Aug-2024 01:42:35
%  MATLAB version: 23.2.0.2668659 (R2023b) Update 9
% -------------------------------------------------------------------
saveVarsMat = load('PMSM.mat');

B = Simulink.Parameter;
B.Value = 0.001889;
B.Complexity = 'real';
B.CoderInfo.StorageClass = 'Auto';
B.Description = '';
B.DataType = 'auto';
B.Min = [];
B.Max = [];
B.DocUnits = '';

C_LUT_AngleTable_sng_Null = saveVarsMat.C_LUT_AngleTable_sng_Null; % <1x1 Simulink.Parameter> C_LUT_AngleTable_sng_Null.Value 中的元素太多

C_LUT_SinTable_sng_Null = saveVarsMat.C_LUT_SinTable_sng_Null; % <1x1 Simulink.Parameter> C_LUT_SinTable_sng_Null.Value 中的元素太多

C_MATH_OneOverSqrtThree_s32n31_Null = Simulink.Parameter;
C_MATH_OneOverSqrtThree_s32n31_Null.Value = 0.57735026918962584;
C_MATH_OneOverSqrtThree_s32n31_Null.Complexity = 'real';
C_MATH_OneOverSqrtThree_s32n31_Null.CoderInfo.StorageClass = 'Auto';
C_MATH_OneOverSqrtThree_s32n31_Null.Description = '';
C_MATH_OneOverSqrtThree_s32n31_Null.DataType = 'fixdt(1,32,31)';
C_MATH_OneOverSqrtThree_s32n31_Null.Min = [];
C_MATH_OneOverSqrtThree_s32n31_Null.Max = [];
C_MATH_OneOverSqrtThree_s32n31_Null.DocUnits = '';

C_MATH_Pi_u32n30_Null = Simulink.Parameter;
C_MATH_Pi_u32n30_Null.Value = 3.1415926535897931;
C_MATH_Pi_u32n30_Null.Complexity = 'real';
C_MATH_Pi_u32n30_Null.CoderInfo.StorageClass = 'Auto';
C_MATH_Pi_u32n30_Null.Description = '';
C_MATH_Pi_u32n30_Null.DataType = 'fixdt(0,32,30)';
C_MATH_Pi_u32n30_Null.Min = [];
C_MATH_Pi_u32n30_Null.Max = [];
C_MATH_Pi_u32n30_Null.DocUnits = '';

C_MATH_SqrtThreeOverThree_s32n31_Null = Simulink.Parameter;
C_MATH_SqrtThreeOverThree_s32n31_Null.Value = 0.57735026918962573;
C_MATH_SqrtThreeOverThree_s32n31_Null.Complexity = 'real';
C_MATH_SqrtThreeOverThree_s32n31_Null.CoderInfo.StorageClass = 'Auto';
C_MATH_SqrtThreeOverThree_s32n31_Null.Description = '';
C_MATH_SqrtThreeOverThree_s32n31_Null.DataType = 'fixdt(1,32,31)';
C_MATH_SqrtThreeOverThree_s32n31_Null.Min = [];
C_MATH_SqrtThreeOverThree_s32n31_Null.Max = [];
C_MATH_SqrtThreeOverThree_s32n31_Null.DocUnits = '';

C_PMSM_CurQKi_u32n31_null = Simulink.Parameter;
C_PMSM_CurQKi_u32n31_null.Value = 0.015707963267949;
C_PMSM_CurQKi_u32n31_null.Complexity = 'real';
C_PMSM_CurQKi_u32n31_null.CoderInfo.StorageClass = 'Auto';
C_PMSM_CurQKi_u32n31_null.Description = '';
C_PMSM_CurQKi_u32n31_null.DataType = 'fixdt(0,32,31)';
C_PMSM_CurQKi_u32n31_null.Min = [];
C_PMSM_CurQKi_u32n31_null.Max = [];
C_PMSM_CurQKi_u32n31_null.DocUnits = '';

C_PMSM_CurQKp_u32n31_null = Simulink.Parameter;
C_PMSM_CurQKp_u32n31_null.Value = 1.9949113350295189;
C_PMSM_CurQKp_u32n31_null.Complexity = 'real';
C_PMSM_CurQKp_u32n31_null.CoderInfo.StorageClass = 'Auto';
C_PMSM_CurQKp_u32n31_null.Description = '';
C_PMSM_CurQKp_u32n31_null.DataType = 'fixdt(0,32,31)';
C_PMSM_CurQKp_u32n31_null.Min = [];
C_PMSM_CurQKp_u32n31_null.Max = [];
C_PMSM_CurQKp_u32n31_null.DocUnits = '';

C_PMSM_Flux_u32n32_Vs = Simulink.Parameter;
C_PMSM_Flux_u32n32_Vs.Value = 0.192;
C_PMSM_Flux_u32n32_Vs.Complexity = 'real';
C_PMSM_Flux_u32n32_Vs.CoderInfo.StorageClass = 'Auto';
C_PMSM_Flux_u32n32_Vs.Description = '';
C_PMSM_Flux_u32n32_Vs.DataType = 'fixdt(0,32,32)';
C_PMSM_Flux_u32n32_Vs.Min = [];
C_PMSM_Flux_u32n32_Vs.Max = [];
C_PMSM_Flux_u32n32_Vs.DocUnits = '';

F = Simulink.Parameter;
F.Value = 500;
F.Complexity = 'real';
F.CoderInfo.StorageClass = 'Auto';
F.Description = '';
F.DataType = 'auto';
F.Min = [];
F.Max = [];
F.DocUnits = '';

FBase_Hz = 200;

F_pu = 2.5;

Flux = 0.192;

FluxBase_Vs = 0.477464829275686;

Flux_pu = 0.40212385965949354;

IBase_A = Simulink.Parameter;
IBase_A.Value = 2000;
IBase_A.Complexity = 'real';
IBase_A.CoderInfo.StorageClass = 'Auto';
IBase_A.Description = '';
IBase_A.DataType = 'auto';
IBase_A.Min = [];
IBase_A.Max = [];
IBase_A.DocUnits = '';

I_pu = 0.73333333333333328;

Id = Simulink.Parameter;
Id.Value = 1;
Id.Complexity = 'real';
Id.CoderInfo.StorageClass = 'Auto';
Id.Description = '';
Id.DataType = 'auto';
Id.Min = [];
Id.Max = [];
Id.DocUnits = '';

Iq = Simulink.Parameter;
Iq.Value = 1;
Iq.Complexity = 'real';
Iq.CoderInfo.StorageClass = 'Auto';
Iq.Description = '';
Iq.DataType = 'auto';
Iq.Min = [];
Iq.Max = [];
Iq.DocUnits = '';

Ireal = 220;

J = 0.011;

JBase_kgmm = 3.158881883127822;

KCCM_VirPosn_flg = Simulink.Parameter;
KCCM_VirPosn_flg.Value = 0;
KCCM_VirPosn_flg.Complexity = 'real';
KCCM_VirPosn_flg.CoderInfo.StorageClass = 'Auto';
KCCM_VirPosn_flg.Description = '';
KCCM_VirPosn_flg.DataType = 'boolean';
KCCM_VirPosn_flg.Min = [];
KCCM_VirPosn_flg.Max = [];
KCCM_VirPosn_flg.DocUnits = '';

KCCM_VoltModeEna_Flg = Simulink.Parameter;
KCCM_VoltModeEna_Flg.Value = 0;
KCCM_VoltModeEna_Flg.Complexity = 'real';
KCCM_VoltModeEna_Flg.CoderInfo.StorageClass = 'Auto';
KCCM_VoltModeEna_Flg.Description = '';
KCCM_VoltModeEna_Flg.DataType = 'boolean';
KCCM_VoltModeEna_Flg.Min = [];
KCCM_VoltModeEna_Flg.Max = [];
KCCM_VoltModeEna_Flg.DocUnits = '';

KCCM_VoltMode_Flg = Simulink.Parameter;
KCCM_VoltMode_Flg.Value = 0;
KCCM_VoltMode_Flg.Complexity = 'real';
KCCM_VoltMode_Flg.CoderInfo.StorageClass = 'Auto';
KCCM_VoltMode_Flg.Description = '';
KCCM_VoltMode_Flg.DataType = 'boolean';
KCCM_VoltMode_Flg.Min = [];
KCCM_VoltMode_Flg.Max = [];
KCCM_VoltMode_Flg.DocUnits = '';

KSMO_EnaEst_Flg = Simulink.Parameter;
KSMO_EnaEst_Flg.Value = 0;
KSMO_EnaEst_Flg.Complexity = 'real';
KSMO_EnaEst_Flg.CoderInfo.StorageClass = 'Auto';
KSMO_EnaEst_Flg.Description = '';
KSMO_EnaEst_Flg.DataType = 'boolean';
KSMO_EnaEst_Flg.Min = [];
KSMO_EnaEst_Flg.Max = [];
KSMO_EnaEst_Flg.DocUnits = '';

K_SVM_DefultDuty_s32n31_Null = Simulink.Parameter;
K_SVM_DefultDuty_s32n31_Null.Value = 0.25;
K_SVM_DefultDuty_s32n31_Null.Complexity = 'real';
K_SVM_DefultDuty_s32n31_Null.CoderInfo.StorageClass = 'Auto';
K_SVM_DefultDuty_s32n31_Null.Description = '';
K_SVM_DefultDuty_s32n31_Null.DataType = 'fixdt(1,32,31)';
K_SVM_DefultDuty_s32n31_Null.Min = [];
K_SVM_DefultDuty_s32n31_Null.Max = [];
K_SVM_DefultDuty_s32n31_Null.DocUnits = '';

K_slide = Simulink.Parameter;
K_slide.Value = 1;
K_slide.Complexity = 'real';
K_slide.CoderInfo.StorageClass = 'Auto';
K_slide.Description = '';
K_slide.DataType = 'double';
K_slide.Min = [];
K_slide.Max = [];
K_slide.DocUnits = '';

Ki_pu = 78.956835208714864;

Kis = 114583.3333333333;

Kp_pu = 6.2671987946917431;

Kps = 57.291666666666657;

Kt = 1.1520000000000001;

LBase_H = 0.0015915494309189533;

LPF_coefg = Simulink.Parameter;
LPF_coefg.Value = 0.01;
LPF_coefg.Complexity = 'real';
LPF_coefg.CoderInfo.StorageClass = 'Auto';
LPF_coefg.Description = '';
LPF_coefg.DataType = 'auto';
LPF_coefg.Min = [];
LPF_coefg.Max = [];
LPF_coefg.DocUnits = '';

Ld = Simulink.Parameter;
Ld.Value = 0.000635;
Ld.Complexity = 'real';
Ld.CoderInfo.StorageClass = 'Auto';
Ld.Description = '';
Ld.DataType = 'auto';
Ld.Min = [];
Ld.Max = [];
Ld.DocUnits = '';

Lq = Simulink.Parameter;
Lq.Value = 0.000685;
Lq.Complexity = 'real';
Lq.CoderInfo.StorageClass = 'Auto';
Lq.Description = '';
Lq.DataType = 'auto';
Lq.Min = [];
Lq.Max = [];
Lq.DocUnits = '';

Ls = 0.000635;

Ls_pu = 0.39898226700590378;

OneOverUBase_V = Simulink.Parameter;
OneOverUBase_V.Value = 0.0016666666666666668;
OneOverUBase_V.Complexity = 'real';
OneOverUBase_V.CoderInfo.StorageClass = 'Auto';
OneOverUBase_V.Description = '';
OneOverUBase_V.DataType = 'fixdt(1,32,31)';
OneOverUBase_V.Min = [];
OneOverUBase_V.Max = [];
OneOverUBase_V.DocUnits = '';

PBase_W = 311769.14536239795;

PU = Simulink.Parameter;
PU.Value = 0.6844444444444443;
PU.Complexity = 'real';
PU.CoderInfo.StorageClass = 'Auto';
PU.Description = '';
PU.DataType = 'auto';
PU.Min = [];
PU.Max = [];
PU.DocUnits = '';

P_pu = Simulink.Parameter;
P_pu.Value = 0.68444444444444441;
P_pu.Complexity = 'real';
P_pu.CoderInfo.StorageClass = 'Auto';
P_pu.Description = '';
P_pu.DataType = 'auto';
P_pu.Min = [];
P_pu.Max = [];
P_pu.DocUnits = '';

Pn = Simulink.Parameter;
Pn.Value = 35000;
Pn.Complexity = 'real';
Pn.CoderInfo.StorageClass = 'Auto';
Pn.Description = '';
Pn.DataType = 'auto';
Pn.Min = [];
Pn.Max = [];
Pn.DocUnits = '';

Pp = Simulink.Parameter;
Pp.Value = 4;
Pp.Complexity = 'real';
Pp.CoderInfo.StorageClass = 'Auto';
Pp.Description = '';
Pp.DataType = 'auto';
Pp.Min = [];
Pp.Max = [];
Pp.DocUnits = '';

Preal = Simulink.Parameter;
Preal.Value = 213388.65949248566;
Preal.Complexity = 'real';
Preal.CoderInfo.StorageClass = 'Auto';
Preal.Description = '';
Preal.DataType = 'auto';
Preal.Min = [];
Preal.Max = [];
Preal.DocUnits = '';

RBase_Ohm = Simulink.Parameter;
RBase_Ohm.Value = 2;
RBase_Ohm.Complexity = 'real';
RBase_Ohm.CoderInfo.StorageClass = 'Auto';
RBase_Ohm.Description = '';
RBase_Ohm.DataType = 'auto';
RBase_Ohm.Min = [];
RBase_Ohm.Max = [];
RBase_Ohm.DocUnits = '';

Rs = Simulink.Parameter;
Rs.Value = 0.05;
Rs.Complexity = 'real';
Rs.CoderInfo.StorageClass = 'Auto';
Rs.Description = '';
Rs.DataType = 'auto';
Rs.Min = [];
Rs.Max = [];
Rs.DocUnits = '';

Rs_pu = Simulink.Parameter;
Rs_pu.Value = 0.025;
Rs_pu.Complexity = 'real';
Rs_pu.CoderInfo.StorageClass = 'Auto';
Rs_pu.Description = '';
Rs_pu.DataType = 'auto';
Rs_pu.Min = [];
Rs_pu.Max = [];
Rs_pu.DocUnits = '';

SBase_W = Simulink.Parameter;
SBase_W.Value = 311769.14536239795;
SBase_W.Complexity = 'real';
SBase_W.CoderInfo.StorageClass = 'Auto';
SBase_W.Description = '';
SBase_W.DataType = 'auto';
SBase_W.Min = [];
SBase_W.Max = [];
SBase_W.DocUnits = '';

SMOGain_V = Simulink.Parameter;
SMOGain_V.Value = 323.31615074619043;
SMOGain_V.Complexity = 'real';
SMOGain_V.CoderInfo.StorageClass = 'Auto';
SMOGain_V.Description = '';
SMOGain_V.DataType = 'auto';
SMOGain_V.Min = [];
SMOGain_V.Max = [];
SMOGain_V.DocUnits = '';

SecPerRnd = Simulink.Parameter;
SecPerRnd.Value = 0.6;
SecPerRnd.Complexity = 'real';
SecPerRnd.CoderInfo.StorageClass = 'Auto';
SecPerRnd.Description = '';
SecPerRnd.DataType = 'auto';
SecPerRnd.Min = [];
SecPerRnd.Max = [];
SecPerRnd.DocUnits = '';

TqBase_Nm = Simulink.Parameter;
TqBase_Nm.Value = 992.39201175922574;
TqBase_Nm.Complexity = 'real';
TqBase_Nm.CoderInfo.StorageClass = 'Auto';
TqBase_Nm.Description = '';
TqBase_Nm.DataType = 'auto';
TqBase_Nm.Min = [];
TqBase_Nm.Max = [];
TqBase_Nm.DocUnits = '';

Ts = Simulink.Parameter;
Ts.Value = 0.0001;
Ts.Complexity = 'real';
Ts.CoderInfo.StorageClass = 'Auto';
Ts.Description = '';
Ts.DataType = 'auto';
Ts.Min = [];
Ts.Max = [];
Ts.DocUnits = '';

Ts_pu = Simulink.Parameter;
Ts_pu.Value = 0.12566370614359174;
Ts_pu.Complexity = 'real';
Ts_pu.CoderInfo.StorageClass = 'Auto';
Ts_pu.Description = '';
Ts_pu.DataType = 'auto';
Ts_pu.Min = [];
Ts_pu.Max = [];
Ts_pu.DocUnits = '';

UBase_V = Simulink.Parameter;
UBase_V.Value = 600;
UBase_V.Complexity = 'real';
UBase_V.CoderInfo.StorageClass = 'Auto';
UBase_V.Description = '';
UBase_V.DataType = 'auto';
UBase_V.Min = [];
UBase_V.Max = [];
UBase_V.DocUnits = '';

U_pu = Simulink.Parameter;
U_pu.Value = 0.93333333333333335;
U_pu.Complexity = 'real';
U_pu.CoderInfo.StorageClass = 'Auto';
U_pu.Description = '';
U_pu.DataType = 'auto';
U_pu.Min = [];
U_pu.Max = [];
U_pu.DocUnits = '';

Ud = Simulink.Parameter;
Ud.Value = 0.05;
Ud.Complexity = 'real';
Ud.CoderInfo.StorageClass = 'Auto';
Ud.Description = '';
Ud.DataType = 'auto';
Ud.Min = [];
Ud.Max = [];
Ud.DocUnits = '';

Udc = Simulink.Parameter;
Udc.Value = 560;
Udc.Complexity = 'real';
Udc.CoderInfo.StorageClass = 'Auto';
Udc.Description = '';
Udc.DataType = 'auto';
Udc.Min = [];
Udc.Max = [];
Udc.DocUnits = '';

Uq = Simulink.Parameter;
Uq.Value = 0.24327;
Uq.Complexity = 'real';
Uq.CoderInfo.StorageClass = 'Auto';
Uq.Description = '';
Uq.DataType = 'auto';
Uq.Min = [];
Uq.Max = [];
Uq.DocUnits = '';

Ureal = Simulink.Parameter;
Ureal.Value = 560;
Ureal.Complexity = 'real';
Ureal.CoderInfo.StorageClass = 'Auto';
Ureal.Description = '';
Ureal.DataType = 'auto';
Ureal.Min = [];
Ureal.Max = [];
Ureal.DocUnits = '';

ZBase_Ohm = Simulink.Parameter;
ZBase_Ohm.Value = 2;
ZBase_Ohm.Complexity = 'real';
ZBase_Ohm.CoderInfo.StorageClass = 'Auto';
ZBase_Ohm.Description = '';
ZBase_Ohm.DataType = 'auto';
ZBase_Ohm.Min = [];
ZBase_Ohm.Max = [];
ZBase_Ohm.DocUnits = '';

dt = Simulink.Parameter;
dt.Value = 1;
dt.Complexity = 'real';
dt.CoderInfo.StorageClass = 'Auto';
dt.Description = '';
dt.DataType = 'auto';
dt.Min = [];
dt.Max = [];
dt.DocUnits = '';

n = Simulink.Parameter;
n.Value = 3000;
n.Complexity = 'real';
n.CoderInfo.StorageClass = 'Auto';
n.Description = '';
n.DataType = 'auto';
n.Min = [];
n.Max = [];
n.DocUnits = '';

nBase_RPM = Simulink.Parameter;
nBase_RPM.Value = 3000;
nBase_RPM.Complexity = 'real';
nBase_RPM.CoderInfo.StorageClass = 'Auto';
nBase_RPM.Description = '';
nBase_RPM.DataType = 'auto';
nBase_RPM.Min = [];
nBase_RPM.Max = [];
nBase_RPM.DocUnits = '';

tBase_s = Simulink.Parameter;
tBase_s.Value = 0.00079577471545947667;
tBase_s.Complexity = 'real';
tBase_s.CoderInfo.StorageClass = 'Auto';
tBase_s.Description = '';
tBase_s.DataType = 'auto';
tBase_s.Min = [];
tBase_s.Max = [];
tBase_s.DocUnits = '';

wBase_rps = Simulink.Parameter;
wBase_rps.Value = 1256.6370614359173;
wBase_rps.Complexity = 'real';
wBase_rps.CoderInfo.StorageClass = 'Auto';
wBase_rps.Description = '';
wBase_rps.DataType = 'auto';
wBase_rps.Min = [];
wBase_rps.Max = [];
wBase_rps.DocUnits = '';

we = Simulink.Parameter;
we.Value = 1;
we.Complexity = 'real';
we.CoderInfo.StorageClass = 'Auto';
we.Description = '';
we.DataType = 'auto';
we.Min = [];
we.Max = [];
we.DocUnits = '';

wmBase_rps = Simulink.Parameter;
wmBase_rps.Value = 314.15926535897933;
wmBase_rps.Complexity = 'real';
wmBase_rps.CoderInfo.StorageClass = 'Auto';
wmBase_rps.Description = '';
wmBase_rps.DataType = 'auto';
wmBase_rps.Min = [];
wmBase_rps.Max = [];
wmBase_rps.DocUnits = '';

clear saveVarsMat;
